name: Publish docs via GitHub Pages
on:
  - pull_request
jobs:
  build:
    name: Check Docs
    runs-on: ubuntu-latest
    if: github.event.label.name != 'area/documentation'
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://${{ secrets.GH_TOKEN }}@github.com/lensapp/mkdocs-material-insiders.git
          pip install mike


      - name: Checkout Release from lens
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git config
        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Extensions API Reference using typedocs
        run: |
           yarn install
           yarn typedocs-extensions-api

      - name: Verify that the markdown is valid
        run: |
          yarn run verify-docs
