name: Check License Header
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
    - name: Install addlicense
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -v -u github.com/google/addlicense
    - name: Check license headers
      run: |
        set -e
        export PATH=${PATH}:`go env GOPATH`/bin

        addlicense -check -l mit -c "OpenLens Authors" *.ts*

        addlicense -check -l mit -c "OpenLens Authors" src/migrations/**/*.ts*
        addlicense -check -l mit -c "OpenLens Authors" src/*.ts*

        addlicense -check -l mit -c "OpenLens Authors" src/common/**/*.ts*
        addlicense -check -l mit -c "OpenLens Authors" src/common/**/*.?css

        addlicense -check -l mit -c "OpenLens Authors" src/main/**/*.ts*

        addlicense -check -l mit -c "OpenLens Authors" src/renderer/**/*.ts*
        addlicense -check -l mit -c "OpenLens Authors" src/renderer/**/*.?css

        addlicense -check -l mit -c "OpenLens Authors" src/extensions/**/*.ts*

        addlicense -check -l mit -c "OpenLens Authors" extensions/**/*.ts*
