name: Publish NPM Package Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version to release manually
jobs:
  publish-extensions:
    name: Publish Extensions NPM Package Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.version }}

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate NPM package
        run: |
          make build-extensions-npm

      - name: Publish NPM package
        run: |
          make publish-extensions-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-library:
    name: Publish Library NPM Package Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.version }}

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate NPM package
        run: |
          make build-library-npm

      - name: Publish NPM package
        run: |
          make publish-library-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
