name: Release Open Lens
on:
  pull_request:
    types:
      - closed
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: |
          echo ${{ github.event.pull_request }}
          exit 1
      - name: Checkout Release from lens
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: butlerlogic/action-autotag@stable
        id: tagger
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - uses: ncipollo/release-action@v1
        if: ${{ needs.tag.outputs.tagname != '' }}
        with:
          name: v${{ steps.open-lens-version.outputs.VERSION }}
          commit: master
          tag: v${{ steps.open-lens-version.outputs.VERSION }}
          body: ${{ github.event.pull_request.body }}
