name: Release Open Lens
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - "release/v*.*"
jobs:
  release:
    name: Release
    if: ${{ github.event.pull_request.merged == 'true' && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: butlerlogic/action-autotag@stable
        id: tagger
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - uses: ncipollo/release-action@v1
        if: ${{ needs.tag.outputs.tagname != '' }}
        with:
          name: v${{ steps.open-lens-version.outputs.VERSION }}
          commit: master
          tag: v${{ steps.open-lens-version.outputs.VERSION }}
          body: ${{ github.event.pull_request.body }}
